---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1eydpfyrjfnzjnsp35wtepwngg63pqda35epkhel6sk4pdrhp3sjq8nqknh
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1eydpfyrjfnzjnsp35wtepwngg63pqda35epkhel6sk4pdrhp3sjq8nqknh
