kind: Secret
ansible_user: ENC[AES256_GCM,data:iAT/2w==,iv:YLdzBDOYUMtOUA/Ey1iubJSgK1qbTNt0TjQ4IbaALPg=,tag:jJLVTctNivP/Lpbi0bOuqQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:XrAJ+6YmXGjAFg==,iv:ez5zcy3O/b2piv4vFE0p+d804RnPDZP8TdaUt8QQesw=,tag:TO6hpqHfb2OOK2EPMIrMNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eydpfyrjfnzjnsp35wtepwngg63pqda35epkhel6sk4pdrhp3sjq8nqknh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K0pLS1BVQ0hBakpBVngv
            Wk5pYXdYSUE3TjV5UElpZldqa2QyWXNXWVJrCmZVU0JlZHNoK2R3K0p4dXY1SFZa
            TUF2ZEFXd3psdi81elFFOVJZQnBHYkkKLS0tIDUzUjA1bE8ycjR5eCtSUjdsN3hj
            WVNPVmZpRmJnQXJUVStpVWhES1Y4dGMKQlKPDSgGCJ1LVoytrUnkfXVKRcdCf06g
            qlvhmSDTQg8/9FpjFFgl2t7TWzye3MHS+3JhTLK5gbehLKVGbjizQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-11T06:15:45Z"
    mac: ENC[AES256_GCM,data:rvGJyVqMfdr++75K3Lc/K9B/N0+7v+Ysb0KZagragyTSpDd6Q/jv2MDseFGYkdRWHE2ad3+mYa4GtVIpgrlfGtd+uCEg1T+5U3silv9xYrfau7aoU8iMzvze8TZshqdTKbrnsWQbiMJsC53/BYV2dcjzLVJbU6yMH1HYT58a7jA=,iv:JS8aJmC7rt53CFusokqMObyQ0KD7dcGjmVXXjohd2Jo=,tag:5O6ZtVddSgnJxNqWtBLybw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
