kind: Secret
ansible_user: ENC[AES256_GCM,data:DxiO7A==,iv:SycH9sRrFpfS44EKfNGeTrCqmx3OHFKxW2fA2HH5uno=,tag:gAx6VehO57VgRyN2ffsTSw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:S6d4RJBNQybmjQ==,iv:zck+hTSSF/X9ZQIZwTGe2UTDN71moSLQhyvURAcdc70=,tag:AeWsHuA8LC48pDUdbIKzPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eydpfyrjfnzjnsp35wtepwngg63pqda35epkhel6sk4pdrhp3sjq8nqknh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY1g5QVl2ckZQOUdueFA2
            bjhoTTk4MGkrV1F3VlhPRkp5U2xtSDJ2K0NBClFxZWVnRlMrVVV0a1hxblhZL0xD
            ZG1nS1ZXUktTbElaOHhDVUcwVWF3SjQKLS0tIHgveXBldGxmaGVhZDVITytnUUY4
            YnFvYTVNT3JSMFFLVy9YcjdUQ2hGYkUKHgEnaGifvOuQLOH00g1hgE+JbwmqmXdK
            SYGZvTNPRICKT4Mqeqs0bpZ0xyLfc2ONnCKcc58ChdONR4hc+UZx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-13T22:34:11Z"
    mac: ENC[AES256_GCM,data:s8TkaW9UhJfYzLdfEtZxSTjAJeHmz1NmcCMAUu0oUtUkAAkRTGVtkPBPJ5tso4SiJIHhBQhh7jWa4RkqOgXcpzN/4LptVAgPVV/4apX0gOgiUP2lFE7r+35eBOfQx3j9KS+gteCAJ9/WfEw8/T6P0ETSZz+1vqOa/O+WbC+hiEQ=,iv:7HsJUpUCfx9lfBZaVnm5h0FDPEx5e6hEtbIUGRXvh68=,tag:iRgcsoDWt7rH5rg+Pf/v6Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
