kind: Secret
ansible_user: ENC[AES256_GCM,data:aEy/fA==,iv:XthkXC5I+11VnmOBlsDINxPhesmg1Z2/Fqwb9R6KPWg=,tag:cytH1JJT4aiZ/JJId9cTaw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:klA2VenrUnpSgg==,iv:thKXTguhpylD0IHaaxj0AYm6/ktzdoE1UeCdY8daKfs=,tag:GJVWa0BaB9pDx+DR7CKpQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eydpfyrjfnzjnsp35wtepwngg63pqda35epkhel6sk4pdrhp3sjq8nqknh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUzZqUGN3bFJtVVhSWXVT
            MUVTTXFTbVVCbXpLZG40VENGRGdzaGlXcm1BCkNJdTY2VWZJaXFWUVdGYmd5Tjg1
            QWR1Y3Z1OUZVUllYVUhnaFlIL1ZmWWcKLS0tIDNmcFNVL3R4T2dCM1BkRXQvSWx3
            L0JpZm5STmJkVzY5eWpQM25VWGVDVEEKUT8FA/fZGZs2WxZoZ/PillH7Ozq7yhUS
            OkVWn1adJA/9SDrVfFMmM8aBoPcoGW2aucIgFXrJwNct/dudHgvFfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-11T06:15:45Z"
    mac: ENC[AES256_GCM,data:KRY1o4A8nTitUCt5ttQNghcoBJ2AY+xkb73+bkukUxAQMds736tugd2/I/30ITY9kK30gUeBeBjoJ0aFQjr4h23ml9CuIzs34hgrcLW3jSL01ccV9Q9eaXxVDV9W89OJTIcvxih9Xtz5xkkspuSHmlt46IUpwk4LWplIAqEiTjM=,iv:TIOvBYs2ZDA2Y65Nj/u9M8l56G8MqourMJfXRXevZvM=,tag:DI8O3Lj9N1s3DF0Hx+Y1Ew==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
